### ISSUE TITLE
validation: detect and verify alt-da provider

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#406]
If DA mode is not Ethereum

* create new file that stores mapping of alt-da byte to provider name
* add-chain: env-var to specify alt-da byte
* validation: check alt-da byte and verify it matches location where data is posted.

**Comment by tessr** [comment]
The idea here is to handle the blue part of the Alt-DA validation check tree: 

![image](https://github.com/user-attachments/assets/5c5746fc-108b-4cdf-89a2-cc0509fffc82)

We could display it like this: 

`superchain/configs/mainnet/lyra.toml`

```toml
name = "Lyra Chain"
chain_id = 957
public_rpc = "https://rpc.lyra.finance"
sequencer_rpc = "https://rpc.lyra.finance"
explorer = "https://explorer.lyra.finance"
superchain_level = 1
standard_chain_candidate = false
data_availability_type = "eth-da" # covered in 410
data_availability_provider = "celestia" # this is the field to add and validate
```

I am also open to this being an enum.
