### ISSUE TITLE
display eth DA / alt DA status

### ISSUE THREAD

**Issue by tessr** [ethereum-optimism/superchain-registry#410]
### Request

The Superchain Registry currently checks whether a chain uses Alt-DA or Eth DA. We should surface this in the machine/human readable files with a new `data_availability_type` field. This field can be set to either `eth-da` or `alt-da`.

For example:

`chainList.toml`: 

```toml
[[chains]]
  name = "OP Mainnet"
  identifier = "mainnet/op"
  chain_id = 10
  rpc = ["https://mainnet.optimism.io"]
  explorers = ["https://explorer.optimism.io"]
  superchain_level = 2
  data_availability_type = "eth-da"
  [chains.parent]
    type = "L2"
    chain = "mainnet"
```

`chainList.json`:

```json
  {
    "name": "OP Mainnet",
    "identifier": "mainnet/op",
    "chainId": 10,
    "rpc": [
      "https://mainnet.optimism.io"
    ],
    "explorers": [
      "https://explorer.optimism.io"
    ],
    "superchainLevel": 2,
    "data_availability_type":"eth-da",
    "parent": {
      "type": "L2",
      "chain": "mainnet"
    }
  },
```

`superchain/configs/op.toml`:
```toml
name = "OP Mainnet"
chain_id = 10
public_rpc = "https://mainnet.optimism.io"
sequencer_rpc = "https://mainnet-sequencer.optimism.io"
explorer = "https://explorer.optimism.io"
superchain_level = 2
standard_chain_candidate = false
data_availability_type = "eth-da"
```

This is **not** blocking the EA launch, but we should populate this data soon after launch because our partners expect to see it.

### Implementation Constraints

We are currently only checking the purple section of the following diagram. If a chain has set a `PlasmaConfig`, they are using Alt-DA Mode. Otherwise, they use Eth DA. 

<img src="https://github.com/user-attachments/assets/992803b9-03b6-4ae6-bb6d-da98e345bf62" width="600" />
<br /><br />

For the gov launch, we should also:

* Determine which DA provider Alt-DA chains are using (e.g., the blue boxes). See also https://github.com/ethereum-optimism/superchain-registry/issues/406
* Perform an onchain check to confirm that batcher transactions are posting calldata/blobdata that matches their stated DA type. See also https://github.com/ethereum-optimism/superchain-registry/issues/400

**Comment by bitwiseguy** [comment]
Could we use this data structure:
```toml
[[chains]]
  name = "OP Mainnet"
  identifier = "mainnet/op"
  chain_id = 10
  rpc = ["https://mainnet.optimism.io"]
  explorers = ["https://explorer.optimism.io"]
  superchain_level = 2
  [chains.data_availability]
    type = "eth-da"
  [chains.parent]
    type = "L2"
    chain = "mainnet"
```
Then for chains using plasma it could look like this (or do we think the keyword `plasma` is needed?):
```toml
[[chains]]
  name = "OP Mainnet"
  identifier = "mainnet/op"
  chain_id = 10
  rpc = ["https://mainnet.optimism.io"]
  explorers = ["https://explorer.optimism.io"]
  superchain_level = 2
  [chains.data_availability]
    type = "alt-da"
    provider = "celestia"
    da_challenge_contract_address = "0x3333333333333333333300000000000000000000"
    da_challenge_window = 5555555
    da_resolve_window = 7777777
  [chains.parent]
    type = "L2"
    chain = "mainnet"
```
