### ISSUE TITLE
feature request: split `[addresses]` key into `[addresse.roles]` and `[addresses.protocol]`

### ISSUE THREAD

**Issue by mds1** [ethereum-optimism/superchain-registry#437]
Right now I find the addresses section hard to read because it's a bit cluttered and there's nothing separating semantically different addresses: 

https://github.com/ethereum-optimism/superchain-registry/blob/c92ef420eec2eaa83001f1fa13dd852bde3bbbf4/superchain/configs/mainnet/op.toml#L31-L53

I would suggest splitting this into `addresses.roles` and `addresses.contracts` keys, as shown below. This would then map nicely to the "roles" section of the [docs](https://docs.optimism.io/chain/security/privileged-roles). It also gives a similar structure to how inputs and outputs will be structured for the OP Stack Manager deployment scripts

I'm open to names other than "protocol" for the other section. I didn't want to use "contracts" as some roles are contracts, but protocol feels like it might be too broad of a term.

```toml
[addresses.roles]
  SystemConfigOwner = "0x847B5c174615B1B7fDF770882256e2D3E95b9D92"
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A"
  Proposer = "0x473300df21D047806A082244b417f96b32f13A33"
  UnsafeBlockSigner = "0xAAAA45d9549EDA09E70937013520214382Ffc4A2"
  BatchSubmitter = "0x6887246668a3b87F54DeB3b94Ba47a6f63F32985"

[addresses.protocol]
  AddressManager = "0xdE1FCfB0851916CA5101820A69b13a4E276bd81F"
  L1CrossDomainMessengerProxy = "0x25ace71c97B33Cc4729CF772ae268934F7ab5fA1"
  L1ERC721BridgeProxy = "0x5a7749f83b81B301cAb5f48EB8516B986DAef23D"
  L1StandardBridgeProxy = "0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1"
  OptimismMintableERC20FactoryProxy = "0x75505a97BD334E7BD3C476893285569C4136Fa0F"
  OptimismPortalProxy = "0xbEb5Fc579115071764c7423A4f12eDde41f106Ed"
  SystemConfigProxy = "0x229047fed2591dbec1eF1118d64F7aF3dB9EB290"
  ProxyAdmin = "0x543bA4AADBAb8f9025686Bd03993043599c6fB04"
  AnchorStateRegistryProxy = "0x18DAc71c228D1C32c99489B7323d441E1175e443"
  DelayedWETHProxy = "0xE497B094d6DbB3D5E4CaAc9a14696D7572588d14"
  DisputeGameFactoryProxy = "0xe5965Ab5962eDc7477C8520243A95517CD252fA9"
  FaultDisputeGame = "0x4146DF64D83acB0DcB0c1a4884a16f090165e122"
  MIPS = "0x0f8EdFbDdD3c0256A80AD8C0F2560B1807873C9c"
  PermissionedDisputeGame = "0xE9daD167EF4DE8812C1abD013Ac9570C616599A0"
  PreimageOracle = "0xD326E10B8186e90F4E2adc5c13a2d0C137ee8b34"
```
