### ISSUE TITLE
Add `optimism` config values to inflight PRs adding chains

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/superchain-registry#532]
Since #510 , we store more information in chain config toml files. But PRs created before that change will not have those fields. 

I propose we write a test which requires the fields exist (we can do this via the Go bindings, although they will use default values for the non pointer types, so 0 for `uints`). Then PRs will be forced to add the data before being merged to main:

Most chains will just add:

```toml
[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250
```

Perhaps we could use any config validation helpers from op-geth to check the values?
