### ISSUE TITLE
store and display contract version

### ISSUE THREAD

**Issue by tessr** [ethereum-optimism/superchain-registry#786]
At the moment, we check the contract versions for chains by querying their RPC endpoint, and we the contract version checks return TRUE if gov-approved and FALSE otherwise.

However, we don't actually persist or display the version number. This is a detail that the Growth team would like to add to the upcoming SCR frontend, and though they’ve agreed to drop the requirement for the v0, it would be great to have this available for a future iteration of the SCR frontend. 

This may also prove useful when doing things like confirming which chains are actually at Stage 1 (see https://github.com/ethereum-optimism/superchain-registry/issues/332). 

Example in chainList.json:

```json
  {
    "name": "OP Mainnet",
    "identifier": "mainnet/op",
    "chainId": 10,
    "rpc": [
      "https://mainnet.optimism.io"
    ],
    "explorers": [
      "https://explorer.optimism.io"
    ],
    "superchainLevel": 1,
    "stage": 1,
    "dataAvailabilityType": "eth-da",
    "parent": {
      "type": "L2",
      "chain": "mainnet"
    }
  },
```

Example in a chain config file:

```toml
name = "OP Mainnet"
chain_id = 10
public_rpc = "https://mainnet.optimism.io"
sequencer_rpc = "https://mainnet-sequencer.optimism.io"
explorer = "https://explorer.optimism.io"
superchain_level = 1
stage = 1
superchain_time = 0 # Missing hardfork times are inherited from superchain.toml
batch_inbox_addr = "0xFF00000000000000000000000000000000000010"
```
